/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Aluno;

/**
 *
 * @author Fellipe e Yuri
 * @since 20/03/2018 - 14:01
 * @version 1.0 Beta Prova
 */
public class UICadAluno extends javax.swing.JFrame {

    Aluno a = new Aluno();
    /**
     * Creates new form UICadAluno
     */
    public UICadAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlN1 = new javax.swing.JLabel();
        jlN2 = new javax.swing.JLabel();
        jlP1 = new javax.swing.JLabel();
        jlP2 = new javax.swing.JLabel();
        jlTotAulas = new javax.swing.JLabel();
        jlNumPre = new javax.swing.JLabel();
        jlDisc = new javax.swing.JLabel();
        jrFeminino = new javax.swing.JRadioButton();
        jrMasculino = new javax.swing.JRadioButton();
        jtNome = new javax.swing.JTextField();
        jtN1 = new javax.swing.JTextField();
        jtN2 = new javax.swing.JTextField();
        jtP1 = new javax.swing.JTextField();
        jtP2 = new javax.swing.JTextField();
        jtTotAulas = new javax.swing.JTextField();
        jtNumPre = new javax.swing.JTextField();
        jcLPV = new javax.swing.JCheckBox();
        jcLPW = new javax.swing.JCheckBox();
        jcLPM = new javax.swing.JCheckBox();
        jcBD = new javax.swing.JCheckBox();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlSexo.setText("Sexo");

        jlN1.setText("N1");

        jlN2.setText("N2");

        jlP1.setText("P1");

        jlP2.setText("P2");

        jlTotAulas.setText("Total de aulas");

        jlNumPre.setText("Numero de Presenças ");

        jlDisc.setText("Disciplinas");

        bgSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("Feminino");
        jrFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemininoKeyPressed(evt);
            }
        });

        bgSexo.add(jrMasculino);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");
        jrMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMasculinoKeyPressed(evt);
            }
        });

        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtN1.setText("0");
        jtN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtN1KeyPressed(evt);
            }
        });

        jtN2.setText("0");
        jtN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtN2KeyPressed(evt);
            }
        });

        jtP1.setText("0");
        jtP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtP1KeyPressed(evt);
            }
        });

        jtP2.setText("0");
        jtP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtP2KeyPressed(evt);
            }
        });

        jtTotAulas.setText("0");
        jtTotAulas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTotAulasKeyPressed(evt);
            }
        });

        jtNumPre.setText("0");
        jtNumPre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNumPreKeyPressed(evt);
            }
        });

        jcLPV.setText("LPV");
        jcLPV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLPVKeyPressed(evt);
            }
        });

        jcLPW.setText("LPW");
        jcLPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLPWKeyPressed(evt);
            }
        });

        jcLPM.setText("LPM");
        jcLPM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLPMKeyPressed(evt);
            }
        });

        jcBD.setText("BD");
        jcBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcBDKeyPressed(evt);
            }
        });

        jLayeredPane1.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlN1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlN2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlP1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlP2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlTotAulas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlNumPre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlDisc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtN1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtN2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtP1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtP2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtTotAulas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNumPre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcLPV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcLPW, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcLPM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcBD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlNumPre)
                        .addGap(18, 18, 18)
                        .addComponent(jtNumPre))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlTotAulas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtTotAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlDisc)
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jcLPM)
                                .addGap(18, 18, 18)
                                .addComponent(jcBD))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jcLPV)
                                .addGap(18, 18, 18)
                                .addComponent(jcLPW))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(18, 18, 18)
                        .addComponent(jtNome))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSexo)
                            .addComponent(jlN1)
                            .addComponent(jlN2))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrMasculino))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlP1)
                                            .addComponent(jlP2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtP2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                            .addComponent(jtP1)))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jrFeminino)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexo)
                    .addComponent(jrFeminino)
                    .addComponent(jrMasculino))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlN1)
                    .addComponent(jlP1)
                    .addComponent(jtN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlN2)
                    .addComponent(jlP2)
                    .addComponent(jtN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTotAulas)
                    .addComponent(jtTotAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumPre)
                    .addComponent(jtNumPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDisc)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcLPV)
                        .addComponent(jcLPW)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcLPM)
                    .addComponent(jcBD))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("CADASTRAR");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("LIMPAR");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbRelatorio.setText("RELATÓRIO");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jbCadastrar)
                .addGap(78, 78, 78)
                .addComponent(jbLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jbRelatorio)
                .addGap(90, 90, 90))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar)
                    .addComponent(jbRelatorio))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cadastrar(){

        a.setNome(jtNome.getText());
        a.setSexo(bgSexo.getSelection().getActionCommand());
        a.setN1(Double.parseDouble(jtN1.getText()));
        a.setN2(Double.parseDouble(jtN2.getText()));
        a.setP1(Double.parseDouble(jtP1.getText()));
        a.setP2(Double.parseDouble(jtP2.getText()));
        a.setTotAulas(Integer.parseInt(jtTotAulas.getText()));
        a.setNumPresencas(Integer.parseInt(jtNumPre.getText()));
        
        ArrayList<String> disc = new ArrayList<>();
        
        if(jcLPV.isSelected()){
            disc.add(jcLPV.getText());
        }//fecha if
        if(jcLPW.isSelected()){
            disc.add(jcLPW.getText());
        }//fecha if
        if(jcLPM.isSelected()){
            disc.add(jcLPM.getText());
        }//fecha if
        if(jcBD.isSelected()){
            disc.add(jcBD.getText());
        }//fecha if
        a.setDisc(disc);
        
        JOptionPane.showMessageDialog(
                this,
                "Cadastrado com sucesso!",
                "Cadastrado :-)",
                JOptionPane.INFORMATION_MESSAGE);
    }//fecha cadastrar
    private void limpar(){
        jtNome.setText("");
        bgSexo.clearSelection();
        jtN1.setText("");
        jtN2.setText("");
        jtP1.setText("");
        jtP2.setText("");
        jtTotAulas.setText("");
        jtNumPre.setText("");
        
        jcLPV.setSelected(false);
        jcLPW.setSelected(false);
        jcLPM.setSelected(false);
        jcBD.setSelected(false);
    }
    private void mostrarRelatorio(){
        JOptionPane.showMessageDialog(
                this,
                "Relatório: \n" + a.toString(),
                "Dados!",
                JOptionPane.PLAIN_MESSAGE);
    }
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        // TODO add your handling code here:
        mostrarRelatorio();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrMasculino.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jrMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMasculinoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrFeminino.grabFocus();
        }
    }//GEN-LAST:event_jrMasculinoKeyPressed

    private void jrFemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemininoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtN1.grabFocus();
        }
    }//GEN-LAST:event_jrFemininoKeyPressed

    private void jtN1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtN1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtP1.grabFocus();
        }
    }//GEN-LAST:event_jtN1KeyPressed

    private void jtN2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtN2KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtP2.grabFocus();
        }
    }//GEN-LAST:event_jtN2KeyPressed

    private void jtP2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtP2KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtTotAulas.grabFocus();
        }
    }//GEN-LAST:event_jtP2KeyPressed

    private void jtTotAulasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTotAulasKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtNumPre.grabFocus();
        }
    }//GEN-LAST:event_jtTotAulasKeyPressed

    private void jtNumPreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumPreKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcLPV.grabFocus();
        }
    }//GEN-LAST:event_jtNumPreKeyPressed

    private void jcLPVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLPVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcLPW.grabFocus();
        }
    }//GEN-LAST:event_jcLPVKeyPressed

    private void jcLPWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLPWKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcLPM.grabFocus();
        }
    }//GEN-LAST:event_jcLPWKeyPressed

    private void jcLPMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLPMKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcBD.grabFocus();
        }
    }//GEN-LAST:event_jcLPMKeyPressed

    private void jcBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcBDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbCadastrar.grabFocus();
        }
    }//GEN-LAST:event_jcBDKeyPressed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbLimpar.grabFocus();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbRelatorio.grabFocus();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jtP1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtP1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtN2.grabFocus();
        }
    }//GEN-LAST:event_jtP1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JCheckBox jcBD;
    private javax.swing.JCheckBox jcLPM;
    private javax.swing.JCheckBox jcLPV;
    private javax.swing.JCheckBox jcLPW;
    private javax.swing.JLabel jlDisc;
    private javax.swing.JLabel jlN1;
    private javax.swing.JLabel jlN2;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumPre;
    private javax.swing.JLabel jlP1;
    private javax.swing.JLabel jlP2;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlTotAulas;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JTextField jtN1;
    private javax.swing.JTextField jtN2;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumPre;
    private javax.swing.JTextField jtP1;
    private javax.swing.JTextField jtP2;
    private javax.swing.JTextField jtTotAulas;
    // End of variables declaration//GEN-END:variables
}
